CREATE TABLE PERSON
(
  ID            BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NAME          VARCHAR(50) NOT NULL,
  ADDRESS_LINE1 VARCHAR(50) NOT NULL,
  ADDRESS_LINE2 VARCHAR(50),
  CITY          VARCHAR(50) NOT NULL,
  ZIP_CODE      VARCHAR(10) NOT NULL
);

INSERT INTO PERSON
VALUES (1, 'John Doe', '1 Linkin Park', NULL, 'Oz', '99999');