CREATE TABLE ADDRESS
(
  ID            BIGINT AUTO_INCREMENT PRIMARY KEY,
  ADDRESS_LINE1 VARCHAR(50),
  ADDRESS_LINE2 VARCHAR(50),
  CITY          VARCHAR(50),
  ZIP_CODE      VARCHAR(10),
  PERSON_ID     BIGINT
);