ALTER TABLE PERSON
  ALTER COLUMN ADDRESS_LINE1 SET NULL;
ALTER TABLE PERSON
  ALTER COLUMN CITY SET NULL;
ALTER TABLE PERSON
  ALTER COLUMN ZIP_CODE SET NULL;

MERGE INTO ADDRESS AS A USING PERSON AS P
  ON (A.PERSON_ID = P.ID)
  WHEN MATCHED THEN
UPDATE SET A.ADDRESS_LINE1 = P.ADDRESS_LINE1,
  A.ADDRESS_LINE2 = P.ADDRESS_LINE2,
  A.CITY = P.CITY,
  A.ZIP_CODE = P.ZIP_CODE
  WHEN NOT MATCHED THEN
INSERT (ADDRESS_LINE1, ADDRESS_LINE2, CITY, ZIP_CODE, PERSON_ID)
VALUES(P.ADDRESS_LINE1, P.ADDRESS_LINE2, P.CITY, P.ZIP_CODE, P.ID);

ALTER TABLE ADDRESS
  ALTER COLUMN ADDRESS_LINE1 SET NOT NULL;
ALTER TABLE ADDRESS
  ALTER COLUMN CITY SET NOT NULL;
ALTER TABLE ADDRESS
  ALTER COLUMN ZIP_CODE SET NOT NULL;
ALTER TABLE ADDRESS
  ALTER COLUMN PERSON_ID SET NOT NULL;